(nlp) nlp@workstation:~/Documents/projects/qa/seq2seq_tf2/bin$ python main.py 
2021-03-05 07:18:05.224709: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-03-05 07:18:06.142173: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-05 07:18:06.142661: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-03-05 07:18:06.192783: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-05 07:18:06.193274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:08:00.0 name: GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.68GHz coreCount: 30 deviceMemorySize: 5.79GiB deviceMemoryBandwidth: 312.97GiB/s
2021-03-05 07:18:06.193328: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-05 07:18:06.193760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:09:00.0 name: GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.68GHz coreCount: 30 deviceMemorySize: 5.79GiB deviceMemoryBandwidth: 312.97GiB/s
2021-03-05 07:18:06.193776: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-03-05 07:18:06.195398: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-03-05 07:18:06.195438: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-03-05 07:18:06.196024: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-03-05 07:18:06.196153: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-03-05 07:18:06.196236: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.1/lib64
2021-03-05 07:18:06.196627: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-03-05 07:18:06.196710: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-03-05 07:18:06.196720: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
max_size of vocab was specified as 30000; we now have 30000 words. Stopping reading.
Finished constructing vocabulary of 30000 total words. Last word added: 肝病毒属
true vocab is  <seq2seq_tf2.batcher.Vocab object at 0x7fa7c6242610>
Creating the batcher ...
2021-03-05 07:18:06.223420: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-05 07:18:06.223695: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-05 07:18:06.223720: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-05 07:18:06.223726: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      
Building the model ...
Creating the checkpoint manager
Initializing from scratch.
Starting the training ...
2021-03-05 07:18:06.729925: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-03-05 07:18:06.730260: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3793115000 Hz
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    main()
  File "main.py", line 88, in main
    train(params)
  File "/home/nlp/Documents/projects/qa/seq2seq_tf2/train_eval_test.py", line 38, in train
    train_model(model, b, params, ckpt, ckpt_manager)
  File "/home/nlp/Documents/projects/qa/seq2seq_tf2/train_helper.py", line 56, in train_model
    loss = train_step(batch[0]["enc_input"],  # shape=(16, 200)
  File "/home/nlp/Documents/projects/qa/seq2seq_tf2/train_helper.py", line 35, in train_step
    pred, _ = model(enc_output,  # shape=(3, 200, 256)
  File "/home/nlp/miniconda3/envs/nlp/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/nlp/Documents/projects/qa/seq2seq_tf2/models/sequence_to_sequence.py", line 34, in call
    context_vector, _ = self.attention(dec_hidden,  # shape=(16, 256)
  File "/home/nlp/miniconda3/envs/nlp/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/nlp/Documents/projects/qa/seq2seq_tf2/decoders/rnn_decoder.py", line 31, in call
    score = self.V*tf.nn.tanh(self.W1(enc_output)+self.W2(hidden_with_time_axis))
  File "/home/nlp/miniconda3/envs/nlp/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1194, in r_binary_op_wrapper
    x = ops.convert_to_tensor(x, dtype=y.dtype.base_dtype, name="x")
  File "/home/nlp/miniconda3/envs/nlp/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/nlp/miniconda3/envs/nlp/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1540, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/nlp/miniconda3/envs/nlp/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 339, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/nlp/miniconda3/envs/nlp/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/home/nlp/miniconda3/envs/nlp/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 276, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/nlp/miniconda3/envs/nlp/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 301, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/nlp/miniconda3/envs/nlp/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (<tensorflow.python.keras.layers.core.Dense object at 0x7fa7dc2afca0>) with an unsupported type (<class 'tensorflow.python.keras.layers.core.Dense'>) to a Tensor.
